import Head from 'next/head'
import Header from '../components/Header/Header'
import Nav from '../components/Nav/Nav'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Nav/>
      <main>
          <h1>hwllo</h1>
      </main>
    </div>
  )
}
